GPIO_RPI5: gpio_rpi5.c File Reference
gpio_rpi5.c File Reference
Direct register access GPIO backend for Raspberry Pi 5.
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/mman.h>
#include "gpio_rpi5.h"
Macros
#define GPIOMEM_DEVICE "/dev/gpiomem0"
Device path for the RP1 GPIO memory region.
#define GPIO_MEM_SIZE 0x30000
Total size of the memory-mapped region (192 KB).
IO Bank Base Offsets
Control and status registers for each GPIO pin.
#define RP1_IO_BANK0 0x00000
GPIO 0–27 control registers.
#define RP1_IO_BANK1 0x04000
GPIO 28–53 control registers.
RIO (Register I/O) Base Offsets
Fast read/write/toggle registers with atomic access support.
#define RP1_SYS_RIO0 0x10000
GPIO 0–27 fast register I/O.
#define RP1_SYS_RIO1 0x14000
GPIO 28–53 fast register I/O.
Pad Control Base Offsets
Drive strength, pull resistor, slew rate, and Schmitt trigger configuration.
#define RP1_PADS_BANK0 0x20000
GPIO 0–27 pad configuration.
#define RP1_PADS_BANK1 0x24000
GPIO 28–53 pad configuration.
Atomic Access Offsets
Added to the RIO base to perform atomic bit operations without read-modify-write.
#define RP1_XOR_OFFSET 0x1000
XOR (toggle) bits in the register.
#define RP1_SET_OFFSET 0x2000
SET (write 1) bits in the register.
#define RP1_CLR_OFFSET 0x3000
CLR (write 0) bits in the register.
RIO Register Offsets
Offsets within each SYS_RIOx block for output, output-enable, and input.
#define RIO_OUT 0x00
Output value register.
#define RIO_OE 0x04
Output enable register (1 = output, 0 = input).
#define RIO_IN 0x08
Input value register (read-only).
IO Bank Per-Pin Register Macros
Each pin occupies 8 bytes: STATUS (4 bytes) + CTRL (4 bytes).
#define GPIO_STATUS(pin_in_bank) ((pin_in_bank) * 8)
STATUS register offset for a pin within its bank.
#define GPIO_CTRL(pin_in_bank) ((pin_in_bank) * 8 + 4)
CTRL register offset for a pin within its bank.
GPIO CTRL Register Fields
#define CTRL_FUNCSEL_MASK 0x1F
FUNCSEL field mask (bits 4:0).
#define CTRL_FUNCSEL_LSB 0
FUNCSEL field LSB position.
#define CTRL_OUTOVER_MASK (0x3 << 12)
Output override field mask.
#define CTRL_OEOVER_MASK (0x3 << 14)
Output-enable override field mask.
PADS Register Macros and Bit Fields
#define PADS_GPIO(pin_in_bank) (0x04 + (pin_in_bank) * 4)
Pad register offset (pin 0 starts at 0x04).
#define PAD_OD_BIT (1 << 7)
Output disable bit.
#define PAD_IE_BIT (1 << 6)
Input enable bit.
#define PAD_DRIVE_MASK (0x3 << 4)
Drive strength field mask.
#define PAD_DRIVE_LSB 4
Drive strength field LSB position.
#define PAD_PUE_BIT (1 << 3)
Pull-up enable bit.
#define PAD_PDE_BIT (1 << 2)
Pull-down enable bit.
#define PAD_SCHMITT_BIT (1 << 1)
Schmitt trigger enable bit.
#define PAD_SLEWFAST_BIT (1 << 0)
Fast slew rate enable bit.
Functions
static uint32_t reg_read (uint32_t byte_offset)
Read a 32-bit hardware register.
static void reg_write (uint32_t byte_offset, uint32_t val)
Write a 32-bit value to a hardware register.
static int pin_to_bank (int pin, uint32_t *io_base, uint32_t *rio_base, uint32_t *pads_base, int *bit)
Resolve a GPIO number (0–53) into its bank-specific parameters.
static int gpio_valid_pin (int pin)
Validate that a pin number is within the RP1 range.
int gpio_init (void)
Initialize the GPIO subsystem (mmap backend).
void gpio_cleanup (void)
Release all GPIO resources (mmap backend).
pin_t pinopen (int pin, int mode)
Open a GPIO pin in the specified direction (mmap backend).
void pinclose (int indx_pin)
Close a GPIO pin and reset it to a safe state (mmap backend).
int pinwrite (int indx_pin, int value)
Write a digital value to a GPIO output pin (mmap backend).
int pinread (int pin)
Read the current logic level of a GPIO pin (mmap backend).
int pintoggle (int pin)
Toggle the output state of a GPIO pin (mmap backend).
int pinpull (int pin, int pull)
Configure the internal pull resistor for a GPIO pin (mmap backend).
int pinalt (int pin, int func)
Set the alternate function (FUNCSEL) for a GPIO pin (mmap backend).
int pin_set_drive (int pin, int strength)
Set the output drive strength for a GPIO pin (mmap backend).
int gpio_pintest (int pin_indx)
Quick pin test: pulse a pin HIGH for 1 second, then LOW (mmap backend).
Variables
static volatile uint32_t * gpio_mmap_base = NULL
Base pointer to the memory-mapped RP1 register region.
static int gpio_mmap_fd = -1
File descriptor for /dev/gpiomem0.
static int gpio_initialized = 0
Initialization flag (1 after successful gpio_init()).
pin_t rpi5_gpio [GPIO_MAX_INDEX+1]
Global array caching the state of all GPIO pins.
Detailed Description
Direct register access GPIO backend for Raspberry Pi 5.
This backend uses memory-mapped I/O (mmap) on /dev/gpiomem0 to access the RP1 southbridge GPIO registers directly from userspace. It provides extremely fast GPIO operations (~10 ns per read/write) compared to the pinctrl CLI backend (~10 ms).
Supported GPIO Range
Only RP1 GPIOs 0–53 are accessible through this backend. For BCM2712 GPIOs (100–135) and AON GPIOs (200–237), use the pinctrl backend instead.
RP1 Memory Map (via /dev/gpiomem0, 192 KB region)
Block Offset Description
IO_BANK0 0x00000 GPIO 0–27 control/status registers
IO_BANK1 0x04000 GPIO 28–53 control/status registers
SYS_RIO0 0x10000 GPIO 0–27 fast register I/O
SYS_RIO1 0x14000 GPIO 28–53 fast register I/O
PADS_BANK0 0x20000 GPIO 0–27 pad configuration
PADS_BANK1 0x24000 GPIO 28–53 pad configuration
Atomic Register Access
The SYS_RIO blocks support atomic SET, CLR, and XOR operations at fixed offsets from the base, allowing glitch-free single-register writes without read-modify-write races.
See also
https://datasheets.raspberrypi.com/rp1/rp1-peripherals.pdf
Compile with: gcc -c gpio_rpi5.c -o gpio_rpi5.o -Wall -Wextra
Definition in file gpio_rpi5.c.
Function Documentation
reg_read()
static uint32_t reg_read (uint32_t byte_offset) inline static
Read a 32-bit hardware register.
Parameters
byte_offset Byte offset from the mapped base address.
Returns
The 32-bit register value.
Definition at line 155 of file gpio_rpi5.c.
References gpio_mmap_base.
Referenced by pin_set_drive(), pinalt(), pinclose(), pinopen(), pinpull(), and pinread().
reg_write()
static void reg_write (uint32_t byte_offset, uint32_t val) inline static
Write a 32-bit value to a hardware register.
Parameters
byte_offset Byte offset from the mapped base address.
val Value to write.
Definition at line 165 of file gpio_rpi5.c.
References gpio_mmap_base.
Referenced by pin_set_drive(), pinalt(), pinclose(), pinopen(), pinpull(), pintoggle(), and pinwrite().
pin_to_bank()
static int pin_to_bank (int pin, uint32_t * io_base, uint32_t * rio_base, uint32_t * pads_base, int * bit) static
Resolve a GPIO number (0–53) into its bank-specific parameters.
The RP1 has two banks: Bank 0 covers GPIO 0–27, Bank 1 covers GPIO 28–53. This function returns the base offsets for IO, RIO, and PADS registers, along with the bit position within the bank.
Parameters
[in] pin GPIO number (0–53).
[out] io_base IO bank base offset.
[out] rio_base RIO bank base offset.
[out] pads_base PADS bank base offset.
[out] bit Bit position of the pin within the bank (0–27).
Returns
0 on success, -1 if the pin is out of the RP1 range.
Definition at line 184 of file gpio_rpi5.c.
References RP1_IO_BANK0, RP1_IO_BANK1, RP1_PADS_BANK0, RP1_PADS_BANK1, RP1_SYS_RIO0, and RP1_SYS_RIO1.
Referenced by pin_set_drive(), pinalt(), pinclose(), pinopen(), pinpull(), pinread(), pintoggle(), and pinwrite().
gpio_valid_pin()
static int gpio_valid_pin (int pin) static
Validate that a pin number is within the RP1 range.
Parameters
pin GPIO number to validate.
Returns
1 if valid (0–53), 0 otherwise.
Definition at line 214 of file gpio_rpi5.c.
Referenced by gpio_pintest(), pin_set_drive(), pinalt(), pinclose(), pinopen(), pinpull(), pinread(), pintoggle(), and pinwrite().
Variable Documentation
gpio_mmap_base
volatile uint32_t* gpio_mmap_base = NULL static
Base pointer to the memory-mapped RP1 register region.
Definition at line 137 of file gpio_rpi5.c.
Referenced by gpio_cleanup(), gpio_init(), reg_read(), and reg_write().
gpio_mmap_fd
int gpio_mmap_fd = -1 static
File descriptor for /dev/gpiomem0.
Definition at line 140 of file gpio_rpi5.c.
Referenced by gpio_cleanup(), and gpio_init().
gpio_initialized
int gpio_initialized = 0 static
Initialization flag (1 after successful gpio_init()).
Definition at line 143 of file gpio_rpi5.c.
Referenced by gpio_cleanup(), gpio_init(), pin_set_drive(), pinalt(), pinclose(), pinopen(), pinpull(), pinread(), pintoggle(), and pinwrite().
rpi5_gpio
pin_t rpi5_gpio[GPIO_MAX_INDEX+1]
Global array caching the state of all GPIO pins.
Definition at line 146 of file gpio_rpi5.c.
Referenced by gpio_init(), pinclose(), pinopen(), pinread(), pintoggle(), and pinwrite().