GPIO_RPI5: gpio_rpi5_pinctrl.c File Reference
gpio_rpi5_pinctrl.c File Reference
Pinctrl CLI fallback GPIO backend for Raspberry Pi 5.
#include <sys/stat.h>
#include <sys/types.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include "gpio_rpi5.h"
Functions
static int gpio_valid_pin (int pin)
Validate that a pin index is within any known GPIO range.
int gpio_init (void)
Initialize the GPIO subsystem (pinctrl backend).
void gpio_cleanup (void)
Release GPIO resources (pinctrl backend).
int gpio_pintest (int pin_indx)
Quick pin test: pulse a pin HIGH for 1 second (pinctrl backend).
pin_t pinopen (int pin, int mode)
Open a GPIO pin in the specified direction (pinctrl backend).
void pinclose (int indx_pin)
Close a GPIO pin and reset to input (pinctrl backend).
int pinwrite (int indx_pin, int value)
Write a digital value to a GPIO pin (pinctrl backend).
int pinread (int pin)
Read the current logic level of a GPIO pin (pinctrl backend).
int pinpull (int pin, int pull)
Configure the internal pull resistor (pinctrl backend).
int pintoggle (int pin)
Toggle the output state of a GPIO pin (pinctrl backend).
int pinalt (int pin, int func)
Set the alternate function for a GPIO pin (pinctrl backend).
int pin_set_drive (int pin, int strength)
Set drive strength — NOT SUPPORTED in the pinctrl backend.
Variables
pin_t rpi5_gpio [GPIO_MAX_INDEX+1]
Global array caching the state of all GPIO pins.
static int gpio_initialized = 0
Initialization flag (1 after successful gpio_init()).
Detailed Description
Pinctrl CLI fallback GPIO backend for Raspberry Pi 5.
This backend executes the pinctrl command-line tool (via popen()) to control GPIO pins. It is significantly slower than the mmap backend (~10 ms per operation due to process spawning) but supports all GPIO ranges:
RP1 GPIOs 0–53 (40-pin header)
BCM2712 GPIOs 100–135 (processor-side)
AON GPIOs 200–237 (always-on domain)
When to Use This Backend
When you need to access GPIOs outside the RP1 range (100–237).
When /dev/gpiomem0 is not available.
For quick prototyping where speed is not critical.
Limitations
pin_set_drive() is not supported (returns -1).
pintoggle() is implemented as pinread() + pinwrite() (two CLI calls).
Compile with: gcc -c gpio_rpi5_pinctrl.c -o gpio_rpi5_pinctrl.o -Wall -Wextra
Definition in file gpio_rpi5_pinctrl.c.
Function Documentation
gpio_valid_pin()
static int gpio_valid_pin (int pin) static
Validate that a pin index is within any known GPIO range.
Unlike the mmap backend (which only supports 0–53), this backend accepts:
0–53 (RP1 GPIOs)
100–135 (BCM2712 GPIOs)
200–237 (AON GPIOs)
Parameters
pin GPIO number to validate.
Returns
1 if valid, 0 otherwise.
Definition at line 52 of file gpio_rpi5_pinctrl.c.
Referenced by gpio_pintest(), pinalt(), pinclose(), pinopen(), pinpull(), pinread(), and pinwrite().
Variable Documentation
rpi5_gpio
pin_t rpi5_gpio[GPIO_MAX_INDEX+1]
Global array caching the state of all GPIO pins.
Definition at line 36 of file gpio_rpi5_pinctrl.c.
Referenced by gpio_init(), pinclose(), pinopen(), pinread(), and pinwrite().
gpio_initialized
int gpio_initialized = 0 static
Initialization flag (1 after successful gpio_init()).
Definition at line 39 of file gpio_rpi5_pinctrl.c.
Referenced by gpio_cleanup(), and gpio_init().