GPIO_RPI5: Core API Functions
Core API Functions
Functions for GPIO initialization, I/O, and configuration.
Functions
int gpio_init (void)
Initialize the GPIO subsystem.
void gpio_cleanup (void)
Release all GPIO resources.
int gpio_pintest (int pin_indx)
Quick pin test: briefly pulses a pin HIGH then LOW.
pin_t pinopen (int pin, int mode)
Open a GPIO pin for use in the specified direction.
void pinclose (int indx_pin)
Close a GPIO pin and reset it to a safe state.
int pinwrite (int indx_pin, int value)
Write a digital value (HIGH or LOW) to a GPIO output pin.
int pinread (int pin)
Read the current logic level of a GPIO pin.
int pintoggle (int pin)
Toggle the output state of a GPIO pin.
int pinpull (int pin, int pull)
Configure the internal pull resistor for a GPIO pin.
int pinalt (int pin, int func)
Set the alternate function (FUNCSEL) for a GPIO pin.
int pin_set_drive (int pin, int strength)
Set the output drive strength for a GPIO pin.
Detailed Description
Functions for GPIO initialization, I/O, and configuration.
Function Documentation
gpio_init()
int gpio_init (void)
Initialize the GPIO subsystem.
Must be called once before any other GPIO function. Opens the memory-mapped device (mmap backend) or prepares internal state (pinctrl backend).
Returns
0 on success, -1 on failure (e.g., /dev/gpiomem0 not accessible).
Initialize the GPIO subsystem.
Opens /dev/gpiomem0 and maps 192 KB of RP1 register space into the process address space. All pin states are reset to UNDEF.
Must be called exactly once before any other GPIO function.
Returns
0 on success, -1 if the device cannot be opened or mmap fails.
Note
Requires read/write access to /dev/gpiomem0 (default on Raspberry Pi OS).
Initialize the GPIO subsystem.
Resets all pin states to UNDEF and sets the initialization flag. Unlike the mmap backend, no device files are opened — each subsequent operation spawns a pinctrl CLI process.
Returns
Always returns 0 (cannot fail).
Definition at line 232 of file gpio_rpi5.c.
References gpio_initialized, gpio_initialized, GPIO_MAX_INDEX, GPIO_MEM_SIZE, gpio_mmap_base, gpio_mmap_fd, GPIOMEM_DEVICE, pin_t::mode, rpi5_gpio, pin_t::state, and UNDEF.
gpio_cleanup()
void gpio_cleanup (void)
Release all GPIO resources.
Unmaps memory (mmap backend) and closes file descriptors. Should be called at program exit or when GPIO access is no longer needed.
Release all GPIO resources.
Unmaps the RP1 register region and closes the /dev/gpiomem0 file descriptor. Safe to call even if gpio_init() was not called or already cleaned up.
Release all GPIO resources.
Clears the initialization flag. No file descriptors or memory mappings need to be released in this backend.
Definition at line 277 of file gpio_rpi5.c.
References gpio_initialized, gpio_initialized, GPIO_MEM_SIZE, gpio_mmap_base, and gpio_mmap_fd.
gpio_pintest()
int gpio_pintest (int pin_indx)
Quick pin test: briefly pulses a pin HIGH then LOW.
Opens the pin as OUTPUT, writes HIGH, waits 1 second, writes LOW, then closes the pin. Useful for verifying that a pin is physically functional.
Parameters
pin_indx GPIO number to test (0–53 for mmap backend).
Returns
0 on success, -1 on error.
Quick pin test: briefly pulses a pin HIGH then LOW.
Opens the pin as OUTPUT, drives it HIGH, waits 1 second, drives LOW, then closes the pin. Useful for visual verification with an LED or logic analyzer.
Parameters
pin_indx GPIO number (0–53) to test.
Returns
0 on success, -1 if the pin is invalid or cannot be opened.
Quick pin test: briefly pulses a pin HIGH then LOW.
Opens the pin as OUTPUT, drives HIGH, waits 1 second, drives LOW, then closes. Executes 4 pinctrl commands total.
Parameters
pin_indx GPIO number to test (0–53, 100–135, or 200–237).
Returns
0 on success, -1 if the pin is invalid or a command fails.
Definition at line 656 of file gpio_rpi5.c.
References gpio_valid_pin(), gpio_valid_pin(), HIGH, LOW, pin_t::mode, OUTPUT, pinclose(), pinopen(), pinwrite(), pin_t::state, and UNDEF.
pinopen()
pin_t pinopen (int pin, int mode)
Open a GPIO pin for use in the specified direction.
Configures the pin as INPUT or OUTPUT by setting the FUNCSEL to SIO mode and adjusting the output-enable register. The pin must be opened before calling pinwrite(), pinread(), or pintoggle().
Parameters
pin GPIO number (0–53 for mmap backend, 0–237 for pinctrl).
mode Direction: INPUT (0) or OUTPUT (1).
Returns
A pin_t struct with the configured mode. On error, both fields are UNDEF.
Open a GPIO pin for use in the specified direction.
Configures the pin for standard GPIO (SIO) operation by:
Setting FUNCSEL to SIO (ALT5) in the IO_BANK CTRL register.
Clearing output/OE overrides so SIO controls the pin.
Enabling input (IE) and clearing output-disable (OD) in the pad register.
Setting or clearing the Output Enable bit via atomic RIO registers.
Parameters
pin GPIO number (0–53).
mode Direction: INPUT (0) or OUTPUT (1).
Returns
pin_t with the configured mode. On error, both fields are UNDEF.
Open a GPIO pin for use in the specified direction.
Runs pinctrl set <pin> op (output) or pinctrl set <pin> ip (input) via popen(). The command spawns a separate process, making this ~1000x slower than the mmap backend.
Parameters
pin GPIO number (0–53, 100–135, or 200–237).
mode Direction: INPUT (0) or OUTPUT (1).
Returns
pin_t with the configured mode. On error, both fields are UNDEF.
Definition at line 305 of file gpio_rpi5.c.
References CTRL_OEOVER_MASK, CTRL_OUTOVER_MASK, GPIO_CTRL, GPIO_FUNC_SIO, gpio_initialized, gpio_valid_pin(), gpio_valid_pin(), pin_t::mode, OUTPUT, PAD_IE_BIT, PADS_GPIO, pin_to_bank(), reg_read(), reg_write(), RIO_OE, RP1_CLR_OFFSET, RP1_SET_OFFSET, rpi5_gpio, and UNDEF.
Referenced by gpio_pintest().
pinclose()
void pinclose (int indx_pin)
Close a GPIO pin and reset it to a safe state.
Sets the pin back to input mode and disconnects the function selector (FUNCSEL = NULL). The internal state is reset to UNDEF.
Parameters
indx_pin GPIO number to close.
Close a GPIO pin and reset it to a safe state.
Clears the Output Enable bit (sets pin to input) and sets FUNCSEL to GPIO_FUNC_NULL (31) to disconnect the pin from all peripherals. The cached state is reset to UNDEF.
Parameters
indx_pin GPIO number (0–53) to close.
Close a GPIO pin and reset it to a safe state.
Runs pinctrl set <pin> ip to reset the pin to a safe input state. The cached mode and state are reset to UNDEF.
Parameters
indx_pin GPIO number to close.
Definition at line 363 of file gpio_rpi5.c.
References GPIO_CTRL, GPIO_FUNC_NULL, gpio_initialized, gpio_valid_pin(), gpio_valid_pin(), pin_t::mode, pin_to_bank(), reg_read(), reg_write(), RIO_OE, RP1_CLR_OFFSET, rpi5_gpio, pin_t::state, and UNDEF.
Referenced by gpio_pintest().
pinwrite()
int pinwrite (int indx_pin, int value)
Write a digital value (HIGH or LOW) to a GPIO output pin.
Uses atomic SET/CLR registers (mmap backend) for glitch-free writes.
Parameters
indx_pin GPIO number (must have been opened as OUTPUT).
value Desired level: HIGH (1) or LOW (0).
Returns
0 on success, -1 on error.
Write a digital value (HIGH or LOW) to a GPIO output pin.
Uses the atomic SET or CLR register on SYS_RIO to change the output level in a single write, avoiding read-modify-write glitches.
Parameters
indx_pin GPIO number (0–53, must have been opened as OUTPUT).
value Desired logic level: HIGH (1) or LOW (0).
Returns
0 on success, -1 on error (invalid pin or not initialized).
Write a digital value (HIGH or LOW) to a GPIO output pin.
Runs pinctrl set <pin> dl (drive low) or pinctrl set <pin> dh (drive high). Implicitly sets the pin as output.
Parameters
indx_pin GPIO number (must be a valid pin).
value Desired level: HIGH (1) or LOW (0).
Returns
0 on success, -1 on error (invalid pin or command failure).
Definition at line 395 of file gpio_rpi5.c.
References gpio_initialized, gpio_valid_pin(), gpio_valid_pin(), LOW, pin_to_bank(), reg_write(), RIO_OUT, RP1_CLR_OFFSET, RP1_SET_OFFSET, rpi5_gpio, and pin_t::state.
Referenced by gpio_pintest(), and pintoggle().
pinread()
int pinread (int pin)
Read the current logic level of a GPIO pin.
Reads the input register regardless of whether the pin is configured as INPUT or OUTPUT (output pins can be read back).
Parameters
pin GPIO number.
Returns
HIGH (1), LOW (0), or -1 on error.
Read the current logic level of a GPIO pin.
Reads the RIO_IN input register and extracts the bit for the given pin. Works on both INPUT and OUTPUT pins (output readback is supported).
Parameters
pin GPIO number (0–53).
Returns
HIGH (1), LOW (0), or -1 on error.
Read the current logic level of a GPIO pin.
Runs pinctrl get <pin> and parses the output for "| lo" or "| hi" to determine the logic level. The pipe delimiter avoids false matches with pin name substrings.
Parameters
pin GPIO number.
Returns
HIGH (1), LOW (0), or -1 on error or if the level cannot be parsed.
Definition at line 431 of file gpio_rpi5.c.
References gpio_initialized, gpio_valid_pin(), gpio_valid_pin(), pin_to_bank(), reg_read(), RIO_IN, rpi5_gpio, and pin_t::state.
Referenced by pintoggle().
pintoggle()
int pintoggle (int pin)
Toggle the output state of a GPIO pin.
Uses the atomic XOR register (mmap backend) for a single-instruction toggle, which is faster and safer than a read-modify-write sequence.
Parameters
pin GPIO number (must have been opened as OUTPUT).
Returns
0 on success, -1 on error.
Toggle the output state of a GPIO pin.
Uses the atomic XOR register on SYS_RIO to flip the output bit in a single write. This is faster and race-free compared to read-modify-write.
Parameters
pin GPIO number (0–53, must have been opened as OUTPUT).
Returns
0 on success, -1 on error.
Toggle the output state of a GPIO pin.
Reads the current level via pinread(), then writes the inverted value via pinwrite(). Requires two pinctrl commands (slower than mmap XOR).
Parameters
pin GPIO number (should have been opened as OUTPUT).
Returns
0 on success, -1 on error.
Definition at line 467 of file gpio_rpi5.c.
References gpio_initialized, gpio_valid_pin(), HIGH, LOW, pin_to_bank(), pinread(), pinwrite(), reg_write(), RIO_OUT, RP1_XOR_OFFSET, rpi5_gpio, and pin_t::state.
pinpull()
int pinpull (int pin, int pull)
Configure the internal pull resistor for a GPIO pin.
Sets pull-up, pull-down, or no-pull on the pin's pad register. Pull resistors ensure a defined logic level when the pin is not actively driven — essential for buttons, open-drain buses, etc.
Parameters
pin GPIO number.
pull One of PULL_UP, PULL_DOWN, or PULL_NONE.
Returns
0 on success, -1 on error.
Configure the internal pull resistor for a GPIO pin.
Modifies the PUE (pull-up enable) and PDE (pull-down enable) bits in the pad register. Both bits are cleared first, then the requested pull is set.
Parameters
pin GPIO number (0–53).
pull Pull mode: PULL_UP (1), PULL_DOWN (2), or PULL_NONE (0).
Returns
0 on success, -1 on error (invalid pin, not initialized, or bad pull value).
Configure the internal pull resistor for a GPIO pin.
Runs pinctrl set <pin> pu|pd|pn to set pull-up, pull-down, or no-pull respectively.
Parameters
pin GPIO number.
pull Pull mode: PULL_UP (1), PULL_DOWN (2), or PULL_NONE (0).
Returns
0 on success, -1 on error.
Definition at line 503 of file gpio_rpi5.c.
References gpio_initialized, gpio_valid_pin(), gpio_valid_pin(), PAD_PDE_BIT, PAD_PUE_BIT, PADS_GPIO, pin_to_bank(), PULL_DOWN, PULL_NONE, PULL_UP, reg_read(), and reg_write().
pinalt()
int pinalt (int pin, int func)
Set the alternate function (FUNCSEL) for a GPIO pin.
Switches the pin from standard GPIO mode to a peripheral function (e.g., SPI, I2C, UART, PWM, PCM). The function number is chip-specific; refer to the RP1 datasheet for the pin-function mapping table.
Parameters
pin GPIO number.
func Alternate function number: ALT0–ALT8, or GPIO_FUNC_NULL (31).
Returns
0 on success, -1 on error.
Set the alternate function (FUNCSEL) for a GPIO pin.
Switches the pin from standard GPIO mode to a hardware peripheral function by writing the function number into the CTRL register's FUNCSEL field. Also enables input and clears output-disable on the pad.
Parameters
pin GPIO number (0–53).
func Alternate function: ALT0–ALT8 (0–8) or GPIO_FUNC_NULL (31).
Returns
0 on success, -1 on error.
Example
pinalt(GPIO2, ALT3);   // Set GPIO2 to I2C1 SDA
pinalt(GPIO3, ALT3);   // Set GPIO3 to I2C1 SCL
Set the alternate function (FUNCSEL) for a GPIO pin.
Runs pinctrl set <pin> a<func> to switch the pin to a hardware peripheral function (SPI, I2C, UART, PWM, etc.).
Parameters
pin GPIO number.
func Alternate function number: 0–8 (ALT0–ALT8) or 31 (NULL/disconnect).
Returns
0 on success, -1 on error.
Example
pinalt(GPIO14, ALT4);  // Set GPIO14 to UART0 TXD
pinalt(GPIO15, ALT4);  // Set GPIO15 to UART0 RXD
Definition at line 564 of file gpio_rpi5.c.
References CTRL_FUNCSEL_MASK, GPIO_CTRL, GPIO_FUNC_NULL, gpio_initialized, gpio_valid_pin(), gpio_valid_pin(), PAD_IE_BIT, PADS_GPIO, pin_to_bank(), reg_read(), and reg_write().
pin_set_drive()
int pin_set_drive (int pin, int strength)
Set the output drive strength for a GPIO pin.
Configures how much current the pin can source or sink. Higher values are needed for driving long traces, LEDs, or fast digital signals.
Parameters
pin GPIO number.
strength One of DRIVE_2MA, DRIVE_4MA, DRIVE_8MA, or DRIVE_12MA.
Returns
0 on success, -1 on error.
Note
Only supported by the mmap backend. The pinctrl backend returns -1.
Set the output drive strength for a GPIO pin.
Modifies the DRIVE field (bits 5:4) in the pad register to control the maximum source/sink current. Higher drive is useful for fast signals (SPI clock) or pins driving long traces.
Parameters
pin GPIO number (0–53).
strength One of: DRIVE_2MA (0), DRIVE_4MA (1), DRIVE_8MA (2), DRIVE_12MA (3).
Returns
0 on success, -1 on error.
Set the output drive strength for a GPIO pin.
The pinctrl CLI does not expose drive strength control. Use the mmap backend (gpio_rpi5.c) if drive strength configuration is required.
Parameters
pin Ignored.
strength Ignored.
Returns
Always returns -1.
Definition at line 614 of file gpio_rpi5.c.
References DRIVE_12MA, gpio_initialized, gpio_valid_pin(), PAD_DRIVE_LSB, PAD_DRIVE_MASK, PADS_GPIO, pin_to_bank(), reg_read(), and reg_write().